version: '3.7'

services:
  # Backend API
  filmik-api:
    container_name: backend
    build: ./
    command: npm run start:dev
    working_dir: /usr/src/filmik-api
    ports:
      - '8000:3000'
    volumes:
      - ./:/usr/src/filmik-api
    env_file:
      - ./.private/secret.env
      - ./.private/api-keys.env
      - ./.private/nodemailer.env
  # Postgres
  postgres:
    container_name: postgres-db
    build: ./postgres
    ports:
      - '5431:5432'
    env_file:
      - ./.private/dbSecret.env
  # Redis
  redis:
    container_name: redis-db
    image: redis
    ports:
      - '6379:6379'
